import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { formatDistanceToNow } from 'date-fns'
import {
  FileOutput,
  Plus,
  Search,
  Filter,
  Inbox,
} from 'lucide-react'
import { cn } from '@/lib/cn'
import { listOutputs } from '@/lib/api'
import { outputsRoute } from '@/lib/routes'
import type { Output, OutputStatus } from '@/types/outputs'
import type { ArtifactType } from '@/types/common'
import PageHeader from '@/components/shared/PageHeader'
import StatusBadge from '@/components/shared/StatusBadge'
import EmptyState from '@/components/shared/EmptyState'
import LoadingSpinner from '@/components/shared/LoadingSpinner'

/* -------------------------------------------------------------------------- */
/* Filter options                                                             */
/* -------------------------------------------------------------------------- */

const STATUS_OPTIONS: { value: OutputStatus | ''; label: string }[] = [
  { value: '', label: 'All Statuses' },
  { value: 'draft', label: 'Draft' },
  { value: 'active', label: 'Active' },
  { value: 'superseded', label: 'Superseded' },
  { value: 'archived', label: 'Archived' },
]

const TYPE_OPTIONS: { value: ArtifactType | ''; label: string }[] = [
  { value: '', label: 'All Types' },
  { value: 'note', label: 'Note' },
  { value: 'summary', label: 'Summary' },
  { value: 'report', label: 'Report' },
  { value: 'plan', label: 'Plan' },
  { value: 'document', label: 'Document' },
  { value: 'code', label: 'Code' },
  { value: 'data', label: 'Data' },
  { value: 'insight', label: 'Insight' },
  { value: 'other', label: 'Other' },
]

/* -------------------------------------------------------------------------- */
/* Type badge helper                                                          */
/* -------------------------------------------------------------------------- */

function TypeBadge({ type }: { type: string }) {
  return (
    <span className="inline-flex items-center rounded-md bg-secondary/10 px-2 py-0.5 font-label text-xs font-medium text-secondary">
      {type.replace(/_/g, ' ')}
    </span>
  )
}

/* -------------------------------------------------------------------------- */
/* Main component                                                             */
/* -------------------------------------------------------------------------- */

export default function OutputsPage() {
  const [searchQuery, setSearchQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState<OutputStatus | ''>('')
  const [typeFilter, setTypeFilter] = useState<ArtifactType | ''>('')

  const outputsQuery = useQuery({
    queryKey: ['outputs', statusFilter, typeFilter, searchQuery],
    queryFn: () =>
      listOutputs({
        ...(statusFilter ? { status: statusFilter } : {}),
        ...(typeFilter ? { artifact_type: typeFilter } : {}),
        ...(searchQuery ? { q: searchQuery } : {}),
        limit: 100,
      }),
  })

  const outputs: Output[] = outputsQuery.data?.outputs ?? []

  return (
    <div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
      <PageHeader title="Outputs" description="Artifacts and outputs generated by automations and agents">
        <Link
          to={outputsRoute() + '?create=true'}
          className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-label text-sm font-medium text-fg-on-primary hover:bg-primary-hover transition-colors"
        >
          <Plus className="h-4 w-4" />
          Create Output
        </Link>
      </PageHeader>

      {/* Filter bar */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-fg-subtle" />
          <input
            type="text"
            placeholder="Search outputs..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full rounded-lg border border-border bg-bg-elevated py-2 pl-9 pr-3 font-body text-sm text-fg placeholder:text-fg-subtle focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
          />
        </div>

        <div className="flex items-center gap-2">
          <Filter className="h-4 w-4 text-fg-subtle" />
          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value as ArtifactType | '')}
            className="rounded-lg border border-border bg-bg-elevated px-3 py-2 font-label text-sm text-fg focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
          >
            {TYPE_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as OutputStatus | '')}
            className="rounded-lg border border-border bg-bg-elevated px-3 py-2 font-label text-sm text-fg focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
          >
            {STATUS_OPTIONS.map((opt) => (
              <option key={opt.value} value={opt.value}>
                {opt.label}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Loading */}
      {outputsQuery.isLoading && (
        <div className="flex justify-center py-16">
          <LoadingSpinner size="lg" />
        </div>
      )}

      {/* Empty state */}
      {!outputsQuery.isLoading && outputs.length === 0 && (
        <EmptyState
          icon={Inbox}
          title="No outputs found"
          description="Outputs will appear here when agents and automations produce them. You can also create outputs manually."
        />
      )}

      {/* Table */}
      {!outputsQuery.isLoading && outputs.length > 0 && (
        <div className="overflow-hidden rounded-lg border border-border/40 bg-bg-elevated">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-border/30">
                <th className="px-5 py-3 font-label text-xs font-medium uppercase tracking-wider text-fg-muted">
                  Title
                </th>
                <th className="px-5 py-3 font-label text-xs font-medium uppercase tracking-wider text-fg-muted">
                  Type
                </th>
                <th className="px-5 py-3 font-label text-xs font-medium uppercase tracking-wider text-fg-muted">
                  Status
                </th>
                <th className="hidden px-5 py-3 font-label text-xs font-medium uppercase tracking-wider text-fg-muted md:table-cell">
                  Version
                </th>
                <th className="hidden px-5 py-3 font-label text-xs font-medium uppercase tracking-wider text-fg-muted lg:table-cell">
                  Source
                </th>
                <th className="px-5 py-3 font-label text-xs font-medium uppercase tracking-wider text-fg-muted">
                  Updated
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/20">
              {outputs.map((output) => (
                <tr key={output.id} className="group transition-colors hover:bg-bg-sunken/40">
                  <td className="px-5 py-4">
                    <Link
                      to={outputsRoute(output.id)}
                      className="font-body text-sm font-medium text-fg hover:text-primary transition-colors"
                    >
                      {output.title || 'Untitled'}
                    </Link>
                    {output.summary && (
                      <p className="mt-0.5 truncate text-xs text-fg-muted max-w-xs">
                        {output.summary}
                      </p>
                    )}
                  </td>
                  <td className="px-5 py-4">
                    <TypeBadge type={output.artifact_type} />
                  </td>
                  <td className="px-5 py-4">
                    <StatusBadge status={output.status} />
                  </td>
                  <td className="hidden px-5 py-4 md:table-cell">
                    <span className="font-mono text-sm text-fg-muted">
                      v{output.current_version_number}
                    </span>
                  </td>
                  <td className="hidden px-5 py-4 lg:table-cell">
                    <span className="font-label text-xs text-fg-muted">
                      {output.creation_mode.replace(/_/g, ' ')}
                    </span>
                  </td>
                  <td className="px-5 py-4">
                    <span className="text-sm text-fg-muted">
                      {output.updated_at
                        ? formatDistanceToNow(new Date(output.updated_at), { addSuffix: true })
                        : '--'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
