"""initial_schema

Revision ID: 001
Revises:
Create Date: 2026-03-13 20:57:24.908178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('endpoint_id', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=200), nullable=True),
    sa.Column('enabled_models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_providers_system_default', 'llm_providers', ['is_system_default'], unique=True, postgresql_where='is_system_default = TRUE')
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=10), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('auth_value_enc', sa.LargeBinary(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('discovered_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='onboarding_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(length=200), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id')
    )
    op.create_table('mcp_tool_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcp_server_id', 'tool_name', name='uq_mcp_tool_overrides')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('llm_provider_id', sa.UUID(), nullable=True),
    sa.Column('llm_model', sa.String(length=200), nullable=True),
    sa.Column('knowledge_intelligence_provider_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_intelligence_model', sa.String(length=200), nullable=True),
    sa.Column('vision_provider_id', sa.UUID(), nullable=True),
    sa.Column('vision_model', sa.String(length=200), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('agent_enabled', sa.Boolean(), nullable=False),
    sa.Column('agent_tool_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_max_tool_loops', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_intelligence_provider_id'], ['llm_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['llm_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vision_provider_id'], ['llm_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_memory_agent', 'agent_memory', ['agent_id', 'is_active'], unique=False)
    op.create_index('idx_agent_memory_workspace', 'agent_memory', ['workspace_id', 'is_active'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('title_locked', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_subagent', sa.Boolean(), nullable=False),
    sa.Column('subagent_agent_id', sa.String(length=100), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_workspace', 'conversations', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('url_title', sa.String(length=500), nullable=True),
    sa.Column('url_description', sa.Text(), nullable=True),
    sa.Column('gist_language', sa.String(length=50), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_title', sa.String(length=500), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_archived', 'knowledge', ['workspace_id', 'is_archived'], unique=False)
    op.create_index('idx_knowledge_type', 'knowledge', ['workspace_id', 'type'], unique=False)
    op.create_index('idx_knowledge_updated', 'knowledge', ['workspace_id', 'updated_at'], unique=False)
    op.create_index('idx_knowledge_workspace', 'knowledge', ['workspace_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('target_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_logs_started', 'task_logs', ['started_at'], unique=False)
    op.create_index('idx_task_logs_type', 'task_logs', ['task_type', 'started_at'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('tool_calls_count', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_exec_status', 'agent_executions', ['status'], unique=False, postgresql_where="status IN ('running', 'paused_hitl', 'queued')")
    op.create_index('idx_agent_exec_workspace', 'agent_executions', ['workspace_id', 'started_at'], unique=False)
    op.create_table('hitl_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(length=255), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hitl_requests_conversation', 'hitl_requests', ['conversation_id'], unique=False)
    op.create_index('idx_hitl_requests_status', 'hitl_requests', ['status', 'created_at'], unique=False)
    op.create_index('idx_hitl_requests_workspace_status', 'hitl_requests', ['workspace_id', 'status'], unique=False)
    op.create_table('knowledge_tags',
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_id', 'tag')
    )
    op.create_index('idx_knowledge_tags_knowledge', 'knowledge_tags', ['knowledge_id'], unique=False)
    op.create_index('idx_knowledge_tags_tag', 'knowledge_tags', ['tag'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thinking', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=200), nullable=True),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('context_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_interrupted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('tool_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_call_logs_conv', 'tool_call_logs', ['conversation_id', 'started_at'], unique=False)
    op.create_index('idx_tool_call_logs_name', 'tool_call_logs', ['tool_name', 'started_at'], unique=False)
    op.create_index('idx_tool_call_logs_ws', 'tool_call_logs', ['workspace_id', 'started_at'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_attachments_message', 'message_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_attachments_message', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('idx_tool_call_logs_ws', table_name='tool_call_logs')
    op.drop_index('idx_tool_call_logs_name', table_name='tool_call_logs')
    op.drop_index('idx_tool_call_logs_conv', table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_knowledge_tags_tag', table_name='knowledge_tags')
    op.drop_index('idx_knowledge_tags_knowledge', table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index('idx_hitl_requests_workspace_status', table_name='hitl_requests')
    op.drop_index('idx_hitl_requests_status', table_name='hitl_requests')
    op.drop_index('idx_hitl_requests_conversation', table_name='hitl_requests')
    op.drop_table('hitl_requests')
    op.drop_index('idx_agent_exec_workspace', table_name='agent_executions')
    op.drop_index('idx_agent_exec_status', table_name='agent_executions', postgresql_where="status IN ('running', 'paused_hitl', 'queued')")
    op.drop_table('agent_executions')
    op.drop_index('idx_task_logs_type', table_name='task_logs')
    op.drop_index('idx_task_logs_started', table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index('idx_knowledge_workspace', table_name='knowledge')
    op.drop_index('idx_knowledge_updated', table_name='knowledge')
    op.drop_index('idx_knowledge_type', table_name='knowledge')
    op.drop_index('idx_knowledge_archived', table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index('idx_conversations_workspace', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_agent_memory_workspace', table_name='agent_memory')
    op.drop_index('idx_agent_memory_agent', table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_table('workspaces')
    op.drop_table('mcp_tool_overrides')
    op.drop_table('tool_permissions')
    op.drop_table('onboarding')
    op.drop_table('mcp_servers')
    op.drop_index('idx_llm_providers_system_default', table_name='llm_providers', postgresql_where='is_system_default = TRUE')
    op.drop_table('llm_providers')
    op.drop_table('config')
    # ### end Alembic commands ###
